export default [
  {
    id : 0,
    title: "워싱톤 생체리(400g내외/10R)",
    image: "assets/images/main/item-01.jpg",
    price: 5680,
    priceRegular: 6000,
    discount: 50,
    state: "일반상품",
  },
  {
    id : 1,
    title: "신선한 고당도 네이블 오렌지(8개/1.5kg내외)",
    image: "assets/images/main/item-02.jpg",
    price: 10000,
    priceRegular: 12000,
    discount: 35,
    state: "신상품",
  },
  {
    id : 2,
    title: "워싱톤 생체리(400g내외/10R)",
    image: "assets/images/main/item-03.jpg",
    price: 10000,
    priceRegular: 12000,
    discount: 20,
    state: "일반상품",
  },
  {
    id : 3,
    title: "새콤달콤 오렌지",
    image: "assets/images/main/item-04.jpg",
    price: 10000,
    priceRegular: 22000,
    discount: 30,
    state: "일반상품",
  },
  {
    id : 4,
    title: "100% 순수한 딸기 2kg",
    image: "assets/images/main/item-05.jpg",
    price: 8000,
    priceRegular: 10000,
    discount: 15,
    state: "신상품",
  },
  {
    id : 5,
    title: "속이 빨간 자몽 15입(2.1kg내외)",
    image: "assets/images/main/item-06.jpg",
    price: 15000,
    priceRegular: 25800,
    discount: 40,
    state: "신상품",
  },
  {
    id : 6,
    title: "워싱톤 수박주스(400g내외/10R)",
    image: "assets/images/main/item-07.jpg",
    price: 5680,
    priceRegular: 6000,
    discount: 50,
    state: "일반상품",
  },
  {
    id : 7,
    title: "저탄소 GAP 스테비 골드키위 (2kg)",
    image: "assets/images/main/item-08.jpg",
    price: 15000,
    priceRegular: 25800,
    discount: 40,
    state: "신상품",
  },
  {
    id : 8,
    title: "햇살담은 아오리사과 (GAP인증)",
    image: "assets/images/main/item-09.jpg",
    price: 15000,
    priceRegular: 25800,
    discount: 40,
    state: "일반상품",
  },
  {
    id : 9,
    title: "테일러 유기농 프룬 (210g)",
    image: "assets/images/main/item-10.jpg",
    price: 15000,
    priceRegular: 25800,
    discount: 40,
    state: "베스트상품",
  },
  {
    id : 10,
    title: "저탄소 아보카도",
    image: "assets/images/main/item-11.jpg",
    price: 15000,
    priceRegular: 25800,
    discount: 40,
    state: "베스트상품",
  },
  {
    id : 11,
    title: "방울 토마토(GAP)",
    image: "assets/images/main/item-12.jpg",
    price: 15000,
    priceRegular: 25800,
    discount: 40,
    state: "베스트상품",
  },
  {
    id : 12,
    title: "베리콕콕 크랜베리스콘 (55g)",
    image: "assets/images/main/item-10.jpg",
    price: 15000,
    priceRegular: 25800,
    discount: 40,
    state: "신상품",
  },
  {
    id : 13,
    title: "통밀이 들어간 굿!모닝빵",
    image: "assets/images/main/item-07.jpg",
    price: 5680,
    priceRegular: 6000,
    discount: 50,
    state: "일반상품",
  },
  {
    id : 14,
    title: "순두부 그라탕 매콤불닭",
    image: "assets/images/main/item-08.jpg",
    price: 12000,
    priceRegular: 15000,
    discount: 22,
    state: "신상품",
  },
  {
    id : 15,
    title: "미트칠리토마토 크로엣지피자",
    image: "assets/images/main/item-09.jpg",
    price: 5000,
    priceRegular: 5200,
    discount: 40,
    state: "베스트상품",
  },
  {
    id : 16,
    title: "순두부 그라탕 클램차우더",
    image: "assets/images/main/item-01.jpg",
    price: 22000,
    priceRegular: 21200,
    discount: 10,
    state: "베스트상품",
  },
  {
    id : 17,
    title: "식물성 함박스테이크",
    image: "assets/images/main/item-04.jpg",
    price: 15000,
    priceRegular: 14000,
    discount: 15,
    state: "신상품",
  },
];